all: prog3_observer.o prog3_client.o prog3_server.o

prog3_observer.o: prog3_observer.c
	gcc -o observer prog3_observer.c -g
prog3_client.o: prog3_participant.c
	gcc -o participant prog3_participant.c -g
prog3_server.o: prog3_server.c
	gcc -o server prog3_server.c -g
